"""
Launch 12 Pre-configured Experiments
-------------------------------------
Easy launcher for running the 12 hand-picked configurations.

Usage:
    # Run single config
    python launch_experiments.py --config 0
    
    # Run multiple configs
    python launch_experiments.py --config 0 1 2 3
    
    # Run all configs
    python launch_experiments.py --all
    
    # See all configs
    python launch_experiments.py --list
    
Author: Zofia Pilitowska (240272)
"""

import argparse
import subprocess
import sys
from configs_12_models import CONFIGS, print_configs_summary


def build_command(config):
    """Build command line from config dict."""
    cmd = [
        sys.executable,  # Use current Python interpreter
        'train_rl.py',
        '--algorithm', config['algorithm'],
        '--total_timesteps', str(config['total_timesteps']),
        '--learning_rate', str(config['learning_rate']),
        '--batch_size', str(config['batch_size']),
        '--n_steps', str(config['n_steps']),
        '--net_arch', config['net_arch'],
        '--gamma', str(config['gamma']),
        '--gae_lambda', str(config['gae_lambda']),
        '--clip_range', str(config['clip_range']),
        '--ent_coef', str(config['ent_coef']),
        '--vf_coef', str(config['vf_coef']),
        '--max_velocity', str(config['max_velocity']),
        '--reward_scale', str(config['reward_scale']),
        '--max_steps', str(config['max_steps']),
        '--n_envs', str(config['n_envs']),
        '--seed', str(config['seed']),
        '--run_name', config['name']
    ]
    
    return cmd


def run_config(config_index, use_gpu=False):
    """Run a single configuration."""
    if config_index < 0 or config_index >= len(CONFIGS):
        print(f"❌ Error: Config index must be 0-{len(CONFIGS)-1}, got {config_index}")
        return False
    
    config = CONFIGS[config_index]
    
    print("\n" + "="*80)
    print(f"LAUNCHING: {config['name']}")
    print("="*80)
    print(f"Config index: {config_index}")
    print(f"Learning rate: {config['learning_rate']:.2e}")
    print(f"Network: {config['net_arch']}")
    print(f"Max velocity: {config['max_velocity']:.3f}")
    print(f"Batch size: {config['batch_size']}")
    print("="*80 + "\n")
    
    # Build command
    cmd = build_command(config)
    
    # Add GPU flag if requested
    if use_gpu:
        cmd.append('--use_gpu')
    
    # Print command for reference
    print("Command:")
    print(' '.join(cmd))
    print()
    
    # Run
    try:
        result = subprocess.run(cmd, check=True)
        print(f"\n✅ {config['name']} completed successfully!")
        return True
    except subprocess.CalledProcessError as e:
        print(f"\n❌ {config['name']} failed with error code {e.returncode}")
        return False
    except KeyboardInterrupt:
        print(f"\n⚠️  {config['name']} interrupted by user")
        return False


def generate_bash_scripts():
    """Generate bash scripts to run all configs."""
    
    # Single script with all commands
    with open('run_all_configs.sh', 'w') as f:
        f.write("#!/bin/bash\n")
        f.write("# Run all 12 configurations sequentially\n")
        f.write("# Generated by launch_experiments.py\n\n")
        
        for i, config in enumerate(CONFIGS):
            f.write(f"\n# Config {i}: {config['name']}\n")
            cmd = build_command(config)
            f.write(' '.join(cmd) + '\n')
    
    # Individual scripts
    for i, config in enumerate(CONFIGS):
        filename = f"run_config_{i:02d}.sh"
        with open(filename, 'w') as f:
            f.write("#!/bin/bash\n")
            f.write(f"# {config['name']}\n\n")
            cmd = build_command(config)
            f.write(' '.join(cmd) + '\n')
    
    print("✅ Generated bash scripts:")
    print("  • run_all_configs.sh (all 12 configs)")
    print("  • run_config_00.sh through run_config_11.sh (individual configs)")
    print("\nTo make executable:")
    print("  chmod +x run_*.sh")
    print("\nTo run:")
    print("  ./run_config_00.sh")
    print("  # or")
    print("  ./run_all_configs.sh")


def generate_parallel_launcher():
    """Generate script to run configs in parallel using GNU parallel."""
    
    with open('run_parallel.sh', 'w') as f:
        f.write("#!/bin/bash\n")
        f.write("# Run multiple configs in parallel using GNU parallel\n")
        f.write("# Install: sudo apt-get install parallel\n")
        f.write("# Usage: ./run_parallel.sh 4  (runs 4 configs in parallel)\n\n")
        
        f.write("JOBS=${1:-4}  # Default to 4 parallel jobs\n\n")
        
        f.write("parallel -j $JOBS --joblog parallel_jobs.log --bar ::: \\\n")
        for i in range(len(CONFIGS)):
            f.write(f"    './run_config_{i:02d}.sh' \\\n")
        f.write("\n")
        
        f.write("echo 'All jobs completed!'\n")
        f.write("echo 'Check parallel_jobs.log for details'\n")
    
    print("\n✅ Generated parallel launcher:")
    print("  • run_parallel.sh")
    print("\nTo use:")
    print("  1. Install GNU parallel: sudo apt-get install parallel")
    print("  2. Make scripts executable: chmod +x run_*.sh")
    print("  3. Run: ./run_parallel.sh 4  (runs 4 configs at once)")


def main():
    parser = argparse.ArgumentParser(description="Launch 12 pre-configured experiments")
    
    parser.add_argument('--config', nargs='+', type=int, metavar='N',
                       help='Config index/indices to run (0-11)')
    parser.add_argument('--all', action='store_true',
                       help='Run all 12 configs sequentially')
    parser.add_argument('--list', action='store_true',
                       help='List all configs and exit')
    parser.add_argument('--generate-scripts', action='store_true',
                       help='Generate bash scripts for all configs')
    parser.add_argument('--use-gpu', action='store_true',
                       help='Add --use_gpu flag to training')
    
    args = parser.parse_args()
    
    # List configs
    if args.list:
        print_configs_summary()
        return
    
    # Generate scripts
    if args.generate_scripts:
        generate_bash_scripts()
        generate_parallel_launcher()
        return
    
    # Run configs
    if args.all:
        print("\n" + "="*80)
        print("RUNNING ALL 12 CONFIGURATIONS SEQUENTIALLY")
        print("="*80)
        print("This will take approximately 24-48 hours")
        print("Press Ctrl+C to cancel\n")
        
        successes = 0
        failures = 0
        
        for i in range(len(CONFIGS)):
            success = run_config(i, args.use_gpu)
            if success:
                successes += 1
            else:
                failures += 1
        
        print("\n" + "="*80)
        print("ALL RUNS COMPLETED")
        print("="*80)
        print(f"Successes: {successes}")
        print(f"Failures: {failures}")
        print("="*80 + "\n")
    
    elif args.config:
        print("\n" + "="*80)
        print(f"RUNNING {len(args.config)} CONFIGURATION(S)")
        print("="*80 + "\n")
        
        successes = 0
        failures = 0
        
        for i in args.config:
            success = run_config(i, args.use_gpu)
            if success:
                successes += 1
            else:
                failures += 1
        
        print("\n" + "="*80)
        print("SELECTED RUNS COMPLETED")
        print("="*80)
        print(f"Successes: {successes}")
        print(f"Failures: {failures}")
        print("="*80 + "\n")
    
    else:
        parser.print_help()
        print("\n" + "="*80)
        print("QUICK START EXAMPLES")
        print("="*80)
        print("# See all configs:")
        print("  python launch_experiments.py --list")
        print("\n# Run config 0 (conservative_small):")
        print("  python launch_experiments.py --config 0")
        print("\n# Run configs 0, 4, and 7:")
        print("  python launch_experiments.py --config 0 4 7")
        print("\n# Run all 12 configs:")
        print("  python launch_experiments.py --all")
        print("\n# Generate bash scripts:")
        print("  python launch_experiments.py --generate-scripts")
        print("="*80 + "\n")


if __name__ == "__main__":
    main()